name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3  # Updated to latest major version

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to latest major version
      with:
        python-version: '3.x'

    - name: Install Pulumi CLI
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "/home/runner/.pulumi/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Set Pulumi Config - AWS Region
      run: pulumi config set aws:region ap-southeast-1  # Explicitly setting the AWS region
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Preview
      uses: pulumi/actions@v3  # Updated to latest major version
      with:
        command: preview
        stack-name: 'dev'
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Pulumi Up
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: pulumi/actions@v3  # Ensure using the latest version that supports Node16
      with:
        command: up
        stack-name: 'dev'
        args: --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
