name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    tags:
      - 'prod-*'
  pull_request:
    branches:
      - main

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/prod-')
    environment:
      name: development

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Pulumi CLI
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "/home/runner/.pulumi/bin" >> $GITHUB_PATH
        pulumi version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Login to Pulumi
      run: pulumi login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Select Stack
      run: |
        pulumi stack select dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Set Pulumi Config - AWS Region
      run: |
        pulumi config set aws:region ap-southeast-1
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Preview
      run: pulumi preview
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Up
      run: pulumi up --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  prod-deploy:
    needs: dev-deploy
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/prod-')
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deployment-url }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Pulumi CLI
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "/home/runner/.pulumi/bin" >> $GITHUB_PATH
        pulumi version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Login to Pulumi
      run: pulumi login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Select Stack
      run: |
        pulumi stack select prod
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Set Pulumi Config - AWS Region
      run: |
        pulumi config set aws:region ap-southeast-1
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Preview
      run: pulumi preview
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi Up
      run: pulumi up --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
